### ISSUE TITLE
Add Functionality to Hamburger Menu for Mobile and Tablet Devices

### ISSUE THREAD

**Issue by n4itik** [n4itik/Dropsushi#1]
**Description:**

Currently, the hamburger menu intended for mobile and tablet devices is not operational.

**Expected Behavior:**

When accessed on mobile or tablet devices, the hamburger menu should function as expected, providing users with navigation options.

**Screenshot:**

<img src="https://github.com/n4itik/Dropsushi/assets/66974007/65b29ae2-0704-4fea-9c1f-1e141dd63c97" height="400">

**Comment by Sn4pe** [comment]
Hi, could you assign me this issue?
